dubbo:
  application:
    name: dubbo-provider
    registry:
      address: zookeeper://192.168.1.6:2181
  protocol:
    name: dubbo
    port: 20881

  metadata-report:
    address: zookeeper://192.168.1.6:2181



